services:
  - type: web
    name: readreceipts-api
    runtime: python
    repo: https://github.com/brentobox88/readreceipts-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_document_ai:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
